version: '3.5'

services:
    sage:
        image: douglasanpa/sage:latest
        container_name: sage
        ports:
            - "80:80"
            - "443:443"
        restart: always
        environment:
            - DB_HOST=mariadb
            - DB_DATABASE=sage
            - DB_USERNAME=sage
            - DB_PASSWORD=sage
            - MAIL_ADMIN=admin@admin.com
            - APP_URL=http://localhost
            - APP_NAME="SAGE - Sistema de Apoio à Gestão de Eventos"
            - MAIL_HOST=smtp.googlemail.com
            - MAIL_PORT=587
            - MAIL_FROM_ADDRESS=admin@admin.com
            - MAIL_FROM_NAME="System Administrator"
            - MAIL_USERNAME=admin@admin.com
            - MAIL_PASSWORD=secret
            - MAIL_ENCRYPTION=tls
            - OAUTH=false
            - IFSP_KEY=
            - IFSP_SECRET=
            - IFSP_REDIRECT_URI=
            - GOOGLE_KEY=
            - GOOGLE_SECRET=
            - GOOGLE_REDIRECT_URI=
            - FACEBOOK_KEY=
            - FACEBOOK_SECRET=
            - FACEBOOK_REDIRECT_URI=

        volumes:
            - ./sage:/src/storage
            - ./sagecert:/etc/letsencrypt
        depends_on:
            - mariadb

    mariadb:
        image: mariadb:10.1
        container_name: mariadb
        restart: always
        expose:
          - "3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=sage
          - MYSQL_USER=sage
          - MYSQL_PASSWORD=sage
        volumes:
          - ./sagedb:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: 'phpmyadmin'
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - '8080:80'
        volumes: 
            - /sessions
        depends_on:
            - mariadb
