version: '3.5'

services:
    sage:
        image: douglasanpa/sage:latest
        container_name: sage
        ports:
            - "8081:80"
        environment:
            - DB_HOST=mariadb
            - DB_DATABASE=sage
            - DB_USERNAME=sage
            - DB_PASSWORD=sage
            - MAIL_ADMIN=admin@admin.com
            - APP_URL=http://localhost:8081
        volumes:
            - ./sage:/src/storage
        depends_on:
            - mariadb

    mariadb:
        image: mariadb
        container_name: mariadb
        restart: always
        expose:
          - "3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=sage
          - MYSQL_USER=sage
          - MYSQL_PASSWORD=sage
        volumes:
          - ./sagedb:/var/lib/mysql
#volumes:
#  sage: {}
#  sagedb: {}
